### ISSUE TITLE
Change engine name to url

### ISSUE THREAD

**Issue by yochem** [neovim/packspec#46]
Hi! This "federated package specification" looks promising.

I noticed one thing: why are the engines also not an URL? It does not seem consistent with other aspects of the spec that are deemed important:

1. Package names are purely _cosmetic_
2. It's a packspec of "artifacts depending on artifacts", and those artifacts all 'live' at an URL
3. Consistency with the `dependencies` field

It however does seem consistent with [package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines), where the engines are also just names instead of URLs

```json5
{
  "name" : "lspconfig", // OPTIONAL cosmetic name, not used for resolution nor filesystem locations.
  "description" : "Quickstart configurations for the Nvim-lsp client", // OPTIONAL
  "engines": {
      "https://github.com/neovim/neovim": "^0.10.0",
      "https://github.com/vim/vim": "^9.1.0"
  },
  "repository": { // REQUIRED
      "type": "git", // reserved for future use
      "url": "https://github.com/neovim/nvim-lspconfig"
  },
  "dependencies" : { // OPTIONAL
    "https://github.com/neovim/neovim" : "0.6.1",
    "https://github.com/lewis6991/gitsigns.nvim" : "0.3"
  },
}
```

Sorry if this is out of the question or does not make sense.

**Comment by justinmk** [comment]
Engines as currently envisioned (i.e. until a strong case is made otherwise) are client-defined "modes". If the client supports the "nvim" engine then it knows how to install packages for nvim. 

Clients must opt-in to supporting a presumably limited set of engines. Whereas URLs are treated by the client transparently.

Thus nothing is gained (afaict) by specifying engines as URLs.
